### ISSUE TITLE
BiLSTM 배포하기

### ISSUE THREAD

**Issue by eubinecto** [eubinecto/the-clean-rnns#28]
# To-do's
- [x]  `explore_fetch_pipline`으로 학습된  BiLSTM 확인해보기
- [x] `cache_pipeline`에 BiLSTM 도 추가하기
- [x] 로컬에서 데모 테스트하기
- [x] 숫자를 4자리수로 변경하기

**Comment by eubinecto** [comment]
<img width="779" alt="image" src="https://user-images.githubusercontent.com/56193069/162187652-43759f0e-4404-48ec-9963-bf9bee67068f.png">

이게 RNN의 기울기 소멸 / 폭주문제를 설명할 수 있을까?  앞부분에서 말한 내용을 잊는 것을 볼 수 있다.

몇가지 발견한 문제점들
-  <eos> 토큰이 필요할 것 같다. 방점이 있냐 없냐에 따라 결과가 크게 달라진다.  (아니면 방점을 제거하는 것도 한가지 방법일수도)

**Comment by eubinecto** [comment]
수지이름도 추가하기
