### ISSUE TITLE
리드미 업데이트

### ISSUE THREAD

**Issue by eubinecto** [eubinecto/the-clean-rnns#29]
## To-do's
- [x] LSTM 테스트하기
- [x] BiLSTM 테스트하기
- [x] 성능비교표에 파라미터 개수 표기하기
- [x] 성능비교표에 학습에 걸린시간 표기하기 (BiLSTM은 성능은 준수해도, LSTM대비 RoI가 그리높지 않음)
- [x] 간단한 튜토리얼 노트북을 작성하기 (직접 wandb에 가입하고, 자신의 wandb 계정에 프로젝트를  진행할 수 있도록 도와주기)

**Comment by eubinecto** [comment]
## LSTM 테스트 결과


## BiLSTM 테스트 결과

**Comment by eubinecto** [comment]
모델  | 파라미터 개수 | 학습 소요시간
--- | --- | ---
RNN | 16.4 M |  18m 19s
LSTM |  16.4 M |  20m 18s
BiLSTM | 16.4 M | 36m 12s
